linters:
  enable:
    - staticcheck
    - unconvert
    - gofmt
    - revive
    - ineffassign
    - unused
    - misspell
    - bodyclose
    - errcheck
    - goimports
    - prealloc
    - tparallel

issues:
  exlude-dirs:
    - vendor
