linters:
  enable:
    - staticcheck
    - unconvert
    - gofmt
    - goimports
    - revive
    - ineffassign
    - unused
    - misspell
    - bodyclose
    - prealloc
    - errcheck
    - tparallel

issues:
  deadline: 2m
  exlude-dirs:
    - vendor
