schema = 3

[mod]
  [mod."github.com/KyleBanks/depth"]
    version = "v1.2.1"
    hash = "sha256-czR52MfeKA2FdStXCebTMQRKT8jaWQcbV214O3j49qU="
  [mod."github.com/PuerkitoBio/purell"]
    version = "v1.1.1"
    hash = "sha256-Hjf8ZNNdwcRd50A9QNrcCj17gu/6f1iKzVTVrrMrojA="
  [mod."github.com/PuerkitoBio/urlesc"]
    version = "v0.0.0-20170810143723-de5bf2ad4578"
    hash = "sha256-nL0/0QM0Pec83vBlwXvQ8g5SvvZnCQgzD1apxfHNGlg="
  [mod."github.com/andybalholm/brotli"]
    version = "v1.0.5"
    hash = "sha256-/qS8wU8yZQJ+uTOg66rEl9s7spxq9VIXF5L1BcaEClc="
  [mod."github.com/go-openapi/jsonpointer"]
    version = "v0.19.5"
    hash = "sha256-rLyvUdTMeQGeWiVsz2ZeyyFjHomeqd0x+ZR77mxi8Ss="
  [mod."github.com/go-openapi/jsonreference"]
    version = "v0.19.6"
    hash = "sha256-yR7L193fc/w/96+S8l4Nv8NwLq1cDsZiNu3TD195naw="
  [mod."github.com/go-openapi/spec"]
    version = "v0.20.4"
    hash = "sha256-upjAukxFt+zpxxt7+X59910T9JgAn39D/5bl5E0Uib0="
  [mod."github.com/go-openapi/swag"]
    version = "v0.19.15"
    hash = "sha256-NWIJ5GDWMbRc9r8ZPy7PiA7lnlTWYgM5NucwRhkP3zs="
  [mod."github.com/gofiber/fiber/v2"]
    version = "v2.52.1"
    hash = "sha256-zfsNbO0NKNRT93w03bW7pOy6TjAaAEfV8sQ/o426+EQ="
  [mod."github.com/gofiber/swagger"]
    version = "v0.1.14"
    hash = "sha256-udeNvbvbGbA1dyP2w2byovVyxZAkUTpgT20FJn3wsOM="
  [mod."github.com/google/go-github/v61"]
    version = "v61.0.0"
    hash = "sha256-ZzWRsX/dnJArCMYb+FC2+JBMvQ2CX2GCO/9LB1EDV3M="
  [mod."github.com/google/go-querystring"]
    version = "v1.1.0"
    hash = "sha256-itsKgKghuX26czU79cK6C2n+lc27jm5Dw1XbIRgwZJY="
  [mod."github.com/google/uuid"]
    version = "v1.6.0"
    hash = "sha256-VWl9sqUzdOuhW0KzQlv0gwwUQClYkmZwSydHG2sALYw="
  [mod."github.com/josharian/intern"]
    version = "v1.0.0"
    hash = "sha256-LJR0QE2vOQ2/2shBbO5Yl8cVPq+NFrE3ers0vu9FRP0="
  [mod."github.com/klauspost/compress"]
    version = "v1.17.0"
    hash = "sha256-Ig86slHz98UbvvkCYK1QXReArAK74T/UNedVq/ZjH5k="
  [mod."github.com/mailru/easyjson"]
    version = "v0.7.6"
    hash = "sha256-lObieB06Ep7xL3Bbc1sxWpAeqH9VH2LXsPIc9uueuXs="
  [mod."github.com/mattn/go-colorable"]
    version = "v0.1.13"
    hash = "sha256-qb3Qbo0CELGRIzvw7NVM1g/aayaz4Tguppk9MD2/OI8="
  [mod."github.com/mattn/go-isatty"]
    version = "v0.0.20"
    hash = "sha256-qhw9hWtU5wnyFyuMbKx+7RB8ckQaFQ8D+8GKPkN3HHQ="
  [mod."github.com/mattn/go-runewidth"]
    version = "v0.0.15"
    hash = "sha256-WP39EU2UrQbByYfnwrkBDoKN7xzXsBssDq3pNryBGm0="
  [mod."github.com/rivo/uniseg"]
    version = "v0.2.0"
    hash = "sha256-GLj0jiGrT03Ept4V6FXCN1yeZ/b6PpS3MEXK6rYQ8Eg="
  [mod."github.com/swaggo/files/v2"]
    version = "v2.0.0"
    hash = "sha256-OJZ0tJn68mn/LBgLnmfb4UsMoviGTpT4sBfa8S9fVrY="
  [mod."github.com/swaggo/swag"]
    version = "v1.16.2"
    hash = "sha256-KBC/L2/pIjhrhUbf0jGLVO7J+TKu/MNMXEEibf9iYkk="
  [mod."github.com/valyala/bytebufferpool"]
    version = "v1.0.0"
    hash = "sha256-I9FPZ3kCNRB+o0dpMwBnwZ35Fj9+ThvITn8a3Jr8mAY="
  [mod."github.com/valyala/fasthttp"]
    version = "v1.51.0"
    hash = "sha256-zABslQE2va3NNxqZK9Co2Z4Cu76qOa8yk+a5cJpK4gs="
  [mod."github.com/valyala/tcplisten"]
    version = "v1.0.0"
    hash = "sha256-aP0CrNH6UNRMhzgA2NgPwKyZs6xry5aDlZnLgGuHZbs="
  [mod."golang.org/x/net"]
    version = "v0.23.0"
    hash = "sha256-ZB4504rtgsHbcRfijjlqt4/2ddb8tyQB5IBn126uVTQ="
  [mod."golang.org/x/oauth2"]
    version = "v0.19.0"
    hash = "sha256-IYdkq8R8BXnwoBt/ZLAMJr0DkLZDMVkjeBJNQ/Z9Bes="
  [mod."golang.org/x/sys"]
    version = "v0.18.0"
    hash = "sha256-bIFhfFp7Sj0E1gcE3X3l/jecCfSRLgrkb8f0Yr6tVR0="
  [mod."golang.org/x/text"]
    version = "v0.14.0"
    hash = "sha256-yh3B0tom1RfzQBf1RNmfdNWF1PtiqxV41jW1GVS6JAg="
  [mod."golang.org/x/tools"]
    version = "v0.7.0"
    hash = "sha256-ZEjfFulQd6U9r4mEJ5RZOnW49NZnQnrCFLMKCgLg7go="
  [mod."gonum.org/v1/gonum"]
    version = "v0.12.0"
    hash = "sha256-DOYwuXJZFiSyjq+u4TwCmMtOqHLGIVXWtavtuuSquqQ="
  [mod."gopkg.in/yaml.v2"]
    version = "v2.4.0"
    hash = "sha256-uVEGglIedjOIGZzHW4YwN1VoRSTK8o0eGZqzd+TNdd0="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.1"
    hash = "sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU="
